In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('C:/Users/vipul/Downloads/mnist_digits_train.csv')
df.head()

,0,1,2,3,4,5,6,7,8,9,...,775,776,777,778,779,780,781,782,783,784
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,5
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,4
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,9


In [3]:
df['784'].unique()

array([5, 0, 4, 1, 9, 2, 3, 6, 7, 8])

**Step 1** - Define the data

In [4]:
X = df.drop(columns = ['784'])
y = df['784']

In [17]:
y

0        5
1        0
2        4
3        1
4        9
        ..
59995    8
59996    3
59997    5
59998    6
59999    8
Name: 784, Length: 60000, dtype: int64

In [20]:
from keras.utils import to_categorical
yt = to_categorical(y)
yt

array([[0., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.]], shape=(60000, 10))

In [5]:
X.shape

(60000, 784)

In [21]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()

Xs = scaler.fit_transform(X)

In [ ]:
#plt.imshow(X.values[90].reshape(28,28) , cmap='gray')
#plt.show()

In [22]:
from sklearn.model_selection import train_test_split
xtrain, xtest, ytrain, ytest = train_test_split(Xs,yt)

In [23]:
xtrain.shape

(45000, 784)

In [27]:
ytrain.shape

(45000, 10)

**Step 2** - Define neural network model

In [28]:
from keras import models, layers

model = models.Sequential()

model.add(layers.Dense(10 , input_shape = (784,)))

model.add(layers.Dense(10 , activation='sigmoid'))

In [29]:
model.summary()

Model: "sequential_5"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense_10 (Dense)                     │ (None, 10)                  │           7,850 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_11 (Dense)                     │ (None, 10)                  │             110 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 7,960 (31.09 KB)

 Trainable params: 7,960 (31.09 KB)

 Non-trainable params: 0 (0.00 B)

**Step 3** - Compile the model

In [32]:
from keras import optimizers
sgd = optimizers.SGD(learning_rate = 0.01)

model.compile(optimizer = sgd, loss = 'categorical_crossentropy', metrics = ['accuracy'])

**Step 4**- Train the model

In [33]:
model.fit(xtrain,ytrain,
         epochs = 10,
         validation_data = (xtest,ytest))

Epoch 1/10
1407/1407 ━━━━━━━━━━━━━━━━━━━━ 16s 10ms/step - accuracy: 0.8506 - loss: 0.5687 - val_accuracy: 0.8799 - val_loss: 0.4445
Epoch 2/10
1407/1407 ━━━━━━━━━━━━━━━━━━━━ 17s 12ms/step - accuracy: 0.8917 - loss: 0.3880 - val_accuracy: 0.8926 - val_loss: 0.3832
Epoch 3/10
1407/1407 ━━━━━━━━━━━━━━━━━━━━ 17s 12ms/step - accuracy: 0.9020 - loss: 0.3467 - val_accuracy: 0.9017 - val_loss: 0.3547
Epoch 4/10
1407/1407 ━━━━━━━━━━━━━━━━━━━━ 17s 12ms/step - accuracy: 0.9078 - loss: 0.3263 - val_accuracy: 0.9029 - val_loss: 0.3401
Epoch 5/10
1407/1407 ━━━━━━━━━━━━━━━━━━━━ 18s 13ms/step - accuracy: 0.9118 - loss: 0.3137 - val_accuracy: 0.9077 - val_loss: 0.3300
Epoch 6/10
1407/1407 ━━━━━━━━━━━━━━━━━━━━ 18s 13ms/step - accuracy: 0.9138 - loss: 0.3048 - val_accuracy: 0.9091 - val_loss: 0.3249
Epoch 7/10
1407/1407 ━━━━━━━━━━━━━━━━━━━━ 18s 13ms/step - accuracy: 0.9163 - loss: 0.2981 - val_accuracy: 0.9109 - val_loss: 0.3181
Epoch 8/10
1407/1407 ━━━━━━━━━━━━━━━━━━━━ 19s 13ms/step - accuracy: 0.9177 -

In [37]:
xtrain.shape

(45000, 784)

In [38]:
model.predict(xtest[10].reshape(1,784))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 253ms/step


array([[7.1706536e-04, 9.9867058e-05, 7.5851007e-05, 1.0912203e-02,
        7.7903980e-01, 2.0105133e-02, 1.2426944e-03, 9.9964011e-01,
        5.6284904e-01, 9.9517012e-01]], dtype=float32)

In [39]:
print(np.argmax(model.predict(xtest[10].reshape(1,784))))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 221ms/step
7


In [ ]:
xtest[10].reshape(28