In [ ]:
a = 7
print(a * 3)

21


In [ ]:
salaries = [30000, 40000, 20000, 10000, 15000]

print(salaries * 2)

[30000, 40000, 20000, 10000, 15000, 30000, 40000, 20000, 10000, 15000]


In [ ]:
l1 = [3 ,2, 6 ,7.1 , 'abc']
l1

[3, 2, 6, 7.1, 'abc']

In [ ]:
l2 = [[2, 3, 5, 6, 7] , [3, 2, 6, 7, 9] , [4, 3, 7, 6, 3]]
print(l2)

[[2, 3, 5, 6, 7], [3, 2, 6, 7, 9], [4, 3, 7, 6, 3]]


In [ ]:
import numpy as np

salary = np.array([30000, 40000, 20000, 10000, 15000])
print(salary)

[30000 40000 20000 10000 15000]


In [ ]:
print(type(salary))

<class 'numpy.ndarray'>


In [ ]:
print(salary * 2)

[60000 80000 40000 20000 30000]


* **Numpy is a library used to handle n-dimensional data and perform numerical operations wherever required**
* **Numpy Arrays are homogeneous (all elements of the same type), while lists are heterogeneous (elements can be different).**

In [ ]:
n1 = np.array([3,5,6,7,8])
print(n1)

[3 5 6 7 8]


In [ ]:
n2 = np.array([3, 5.1, 6, 7, 8])
print(n2)

[3.  5.1 6.  7.  8. ]


In [ ]:
n3 = np.array([3, 5.1, '6', 7, 8])
print(n3)

['3' '5.1' '6' '7' '8']


In [ ]:
n1 = np.array([3,5,6,7,8])
print(n1)

[3 5 6 7 8]


In [ ]:
print(n1.ndim)
print(n1.shape)

1
(5,)


In [ ]:
n2 = np.array([[2, 3, 5, 6, 7] , [3, 2, 6, 7, 9] , [4, 3, 17, 6, 3]])
print(n2)

[[ 2  3  5  6  7]
 [ 3  2  6  7  9]
 [ 4  3 17  6  3]]


In [ ]:
print(n2.ndim)
print(n2.shape)

2
(3, 5)


**numpy functions**

In [ ]:
print(n2)

[[ 2  3  5  6  7]
 [ 3  2  6  7  9]
 [ 4  3 17  6  3]]


In [ ]:
print(np.sum(n2))
print(np.prod(n2))
print(np.mean(n2))
print(np.min(n2))
print(np.max(n2))
print(np.std(n2))
print(np.argmin(n2))
print(np.argmax(n2))

83
10493400960
5.533333333333333
2
17
3.6672726771933513
0
12


In [ ]:
83/15

5.533333333333333

In [ ]:
#Calculate for each row of matrix
print(np.sum(n2 , axis=1))
print(np.prod(n2 , axis=1))
print(np.mean(n2 , axis=1))
print(np.min(n2 , axis=1))
print(np.max(n2 , axis=1))
print(np.std(n2 , axis=1))
print(np.argmin(n2 , axis=1))
print(np.argmax(n2 , axis=1))

[23 27 33]
[1260 2268 3672]
[4.6 5.4 6.6]
[2 2 3]
[ 7  9 17]
[1.8547237  2.57681975 5.3141321 ]
[0 1 1]
[4 4 2]


In [ ]:
#Calculate for each row of matrix
print(np.sum(n2 , axis=0))
print(np.prod(n2 , axis=0))
print(np.mean(n2 , axis=0))
print(np.min(n2 , axis=0))
print(np.max(n2 , axis=0))
print(np.std(n2 , axis=0))
print(np.argmin(n2 , axis=0))
print(np.argmax(n2 , axis=0))

[ 9  8 28 19 19]
[ 24  18 510 252 189]
[3.         2.66666667 9.33333333 6.33333333 6.33333333]
[2 2 5 6 3]
[ 4  3 17  7  9]
[0.81649658 0.47140452 5.43650214 0.47140452 2.49443826]
[0 1 0 0 2]
[2 0 2 1 1]


In [ ]:
print(n2)

[[ 2  3  5  6  7]
 [ 3  2  6  7  9]
 [ 4  3 17  6  3]]


In [ ]:
#indexing in numpy array
print(n2[2,3])

6


In [ ]:
print(np.where(n2 == 9))

(array([1]), array([4]))


In [ ]:
print(np.where(n2 == 6))

(array([0, 1, 2]), array([3, 2, 3]))


**slicing in numpy array**

In [ ]:
n1 = np.array([3,4,6,7,2,7,1,9,5])
print(n1)

[3 4 6 7 2 7 1 9 5]


In [ ]:
print(n1[3 : 3+5])
print(n1[3 : 8])

[7 2 7 1 9]
[7 2 7 1 9]


In [ ]:
n2 = np.array([[3,4,6,7,2,7,1,9,5] , [13,14,16,17,21,71,11,91,51] , [23,24,26,72,22,72,12,92,52],
               [123,124,261,721,212,712,112,192,152], [123,214,261,721,212,712,112,912,521]])
print(n2)

[[  3   4   6   7   2   7   1   9   5]
 [ 13  14  16  17  21  71  11  91  51]
 [ 23  24  26  72  22  72  12  92  52]
 [123 124 261 721 212 712 112 192 152]
 [123 214 261 721 212 712 112 912 521]]


In [ ]:
print(n2[1:4 , 0:4])

[[ 13  14  16  17]
 [ 23  24  26  72]
 [123 124 261 721]]


In [ ]:
print(n2[1:4, 4:7])

[[ 21  71  11]
 [ 22  72  12]
 [212 712 112]]


In [ ]:
print(n2[: , 8:])

[[  5]
 [ 51]
 [ 52]
 [152]
 [521]]


In [ ]:
#Last column
print(n2[:,-1:])

[[  5]
 [ 51]
 [ 52]
 [152]
 [521]]


In [ ]:
#Last two columns
print(n2[:,-2:])

[[  9   5]
 [ 91  51]
 [ 92  52]
 [192 152]
 [912 521]]


In [ ]:
#Last row
print(n2[-1:,:])

[[123 214 261 721 212 712 112 912 521]]


In [ ]:
#Last two rows
print(n2[-2:,:])

[[123 124 261 721 212 712 112 192 152]
 [123 214 261 721 212 712 112 912 521]]


**Broadcasting**

  * Smaller array should have
    * single value or a scaler
    * single row with number of columns equals to number of columns in larger array
    * Single column with number of rows eqauls to number of rows in smaller array
    * both the array have same shape

In [ ]:
n3 = np.array([[3,2,6,1] , [2,4,1,6] , [3,5,2,7]])
print(n3)

[[3 2 6 1]
 [2 4 1 6]
 [3 5 2 7]]


In [ ]:
k = 7

In [ ]:
print(n3 + 7)

[[10  9 13  8]
 [ 9 11  8 13]
 [10 12  9 14]]


In [ ]:
l = [3,1,2,1]

print(n3 + l)

[[6 3 8 2]
 [5 5 3 7]
 [6 6 4 8]]


In [ ]:
print(n3)

[[3 2 6 1]
 [2 4 1 6]
 [3 5 2 7]]


In [ ]:
m = [[2],[1],[2]]
print(n3 + m)

[[5 4 8 3]
 [3 5 2 7]
 [5 7 4 9]]


In [ ]:
print(n3)

[[3 2 6 1]
 [2 4 1 6]
 [3 5 2 7]]


In [ ]:
x = [3,2,1]
print(n3 + x)

ValueError: operands could not be broadcast together with shapes (3,4) (3,) 

In [ ]:
x = [[3,2,1,2] , [3,2,1,2]]
print(n3 + x)

ValueError: operands could not be broadcast together with shapes (3,4) (2,4) 

In [ ]:
print(n3)

[[3 2 6 1]
 [2 4 1 6]
 [3 5 2 7]]


In [ ]:
n4 = np.array([[3,2,1,2] , [2,1,4,3] , [1,2,2,1]])
print(n4)

[[3 2 1 2]
 [2 1 4 3]
 [1 2 2 1]]


In [ ]:
print(n3 + n4)

[[6 4 7 3]
 [4 5 5 9]
 [4 7 4 8]]


**functions in numpy**

In [ ]:
np.zeros((4,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
n5 = np.arange(0,36)
print(n5)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35]


In [ ]:
print(n5.shape)

(36,)


In [ ]:
#36 => (1,36) , (36,1) , (2,18) , (18,2) , (3,12) , (12,3) , (4,9) , (9,4) , (6,6)
n6 = n5.reshape(4,9)
print(n6)

[[ 0  1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16 17]
 [18 19 20 21 22 23 24 25 26]
 [27 28 29 30 31 32 33 34 35]]


**dot product**

In [ ]:
a = np.array([[2,3,4,1] , [3,2,4,1] , [2,1,3,2]])
print(a)

[[2 3 4 1]
 [3 2 4 1]
 [2 1 3 2]]


In [ ]:
b = np.array([[2,1,2,3] , [2,3,2,2]])
print(b)

[[2 1 2 3]
 [2 3 2 2]]


In [ ]:
print(b.reshape(4,2))

[[2 1]
 [2 3]
 [2 3]
 [2 2]]


In [ ]:
print(b.T)

[[2 2]
 [1 3]
 [2 2]
 [3 2]]


In [ ]:
np.dot(a,b.T)

array([[18, 23],
       [19, 22],
       [17, 17]])

* 3x + 2y + z = 10
* x + y + z = 7
* 2x + y + 4z = 15

In [ ]:
A = np.array([[3, 2, 1] , [1, 1, 1] , [2, 1, 4]])
print(A)

[[3 2 1]
 [1 1 1]
 [2 1 4]]


In [ ]:
X = np.array([['x'],['y'],['z']])
print(X)

[['x']
 ['y']
 ['z']]


In [ ]:
B = np.array([[10],[7],[15]])
print(B)

[[10]
 [ 7]
 [15]]


In [ ]:
#A.X = B
#X = inv(A).B

In [ ]:
Ainv = np.linalg.inv(A)
print(Ainv)

[[ 0.75 -1.75  0.25]
 [-0.5   2.5  -0.5 ]
 [-0.25  0.25  0.25]]


In [ ]:
X = np.dot(Ainv,B)
print(X)

[[-1.]
 [ 5.]
 [ 3.]]


In [ ]:
print(np.dot(A, X))

[[10.]
 [ 7.]
 [15.]]


**stacking**

  * vertical stack
  * horizontal stack

In [ ]:
x1 = np.array([[3,2,1,4],[4,2,5,4],[4,2,7,6]])
print(x1)

[[3 2 1 4]
 [4 2 5 4]
 [4 2 7 6]]


In [ ]:
x2 = np.array([[2,1,3],[1,2,1],[3,4,3]])
print(x2)

[[2 1 3]
 [1 2 1]
 [3 4 3]]


In [ ]:
x3 = np.array([[2,1,3,4],[2,1,1,2]])
print(x3)

[[2 1 3 4]
 [2 1 1 2]]


In [ ]:
#Vertical stacking
array_vstack = np.vstack((x1,x3))
print(array_vstack)

[[3 2 1 4]
 [4 2 5 4]
 [4 2 7 6]
 [2 1 3 4]
 [2 1 1 2]]


In [ ]:
np.concatenate((x1,x3) , axis=0)

array([[3, 2, 1, 4],
       [4, 2, 5, 4],
       [4, 2, 7, 6],
       [2, 1, 3, 4],
       [2, 1, 1, 2]])

In [ ]:
#Horizontal stacking
array_hstack = np.hstack((x1,x2))
print(array_hstack)

[[3 2 1 4 2 1 3]
 [4 2 5 4 1 2 1]
 [4 2 7 6 3 4 3]]


In [ ]:
np.concatenate((x1,x2) , axis=1)

array([[3, 2, 1, 4, 2, 1, 3],
       [4, 2, 5, 4, 1, 2, 1],
       [4, 2, 7, 6, 3, 4, 3]])